### ISSUE TITLE
Move this pack to StackStorm-exchange

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-kafka#9]
- [ ] Update it to wok with recent st2 pack-related breaking changes
- [ ] Move under `stackstorm-exchange` org

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1492461729683362

**Comment by LindsayHill** [comment]
Pack updated here: https://github.com/StackStorm-Exchange/exchange-incubator/issues/11

And now moved to https://github.com/StackStorm-Exchange/stackstorm-kafka
